runtime: python39

instance_class: F2

# Health check configuration
health_check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4

# Use Gunicorn for production
entrypoint: gunicorn -b :$PORT app:app

handlers:
  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto